# Example secrets file for local development
# Replace with actual keys for deployment
# Don't commit actual secrets to your repository

# OpenAI API Key (replace with your own key or use Streamlit Cloud Secrets)
OPENAI_API_KEY = "replace_this_with_your_key"